// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package KasperCommons.Authenticator.KasperCommons.Authenticator;

public final class PacketOuterClass {
  private PacketOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KasperCommons.Authenticator.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 header = 1;</code>
     * @return The header.
     */
    int getHeader();

    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    int getArgsCount();
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    boolean containsArgs(
        java.lang.String key);
    /**
     * Use {@link #getArgsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getArgs();
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getArgsMap();
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    /* nullable */
java.lang.String getArgsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    java.lang.String getArgsOrThrow(
        java.lang.String key);

    /**
     * <code>string data = 3;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 3;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>int32 exception = 4;</code>
     * @return The exception.
     */
    int getException();

    /**
     * <code>string exception_message = 5;</code>
     * @return The exceptionMessage.
     */
    java.lang.String getExceptionMessage();
    /**
     * <code>string exception_message = 5;</code>
     * @return The bytes for exceptionMessage.
     */
    com.google.protobuf.ByteString
        getExceptionMessageBytes();
  }
  /**
   * Protobuf type {@code KasperCommons.Authenticator.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KasperCommons.Authenticator.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      data_ = "";
      exceptionMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetArgs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PacketOuterClass.Packet.class, PacketOuterClass.Packet.Builder.class);
    }

    public interface ArgsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:KasperCommons.Authenticator.Packet.Args)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      java.lang.String getPath();
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      com.google.protobuf.ByteString
          getPathBytes();

      /**
       * <code>string uri = 2;</code>
       * @return The uri.
       */
      java.lang.String getUri();
      /**
       * <code>string uri = 2;</code>
       * @return The bytes for uri.
       */
      com.google.protobuf.ByteString
          getUriBytes();

      /**
       * <code>string match_path = 3;</code>
       * @return The matchPath.
       */
      java.lang.String getMatchPath();
      /**
       * <code>string match_path = 3;</code>
       * @return The bytes for matchPath.
       */
      com.google.protobuf.ByteString
          getMatchPathBytes();
    }
    /**
     * Protobuf type {@code KasperCommons.Authenticator.Packet.Args}
     */
    public static final class Args extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:KasperCommons.Authenticator.Packet.Args)
        ArgsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Args.newBuilder() to construct.
      private Args(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Args() {
        path_ = "";
        uri_ = "";
        matchPath_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Args();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_Args_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_Args_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PacketOuterClass.Packet.Args.class, PacketOuterClass.Packet.Args.Builder.class);
      }

      public static final int PATH_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object path_ = "";
      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      @java.lang.Override
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int URI_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object uri_ = "";
      /**
       * <code>string uri = 2;</code>
       * @return The uri.
       */
      @java.lang.Override
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        }
      }
      /**
       * <code>string uri = 2;</code>
       * @return The bytes for uri.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MATCH_PATH_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object matchPath_ = "";
      /**
       * <code>string match_path = 3;</code>
       * @return The matchPath.
       */
      @java.lang.Override
      public java.lang.String getMatchPath() {
        java.lang.Object ref = matchPath_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matchPath_ = s;
          return s;
        }
      }
      /**
       * <code>string match_path = 3;</code>
       * @return The bytes for matchPath.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMatchPathBytes() {
        java.lang.Object ref = matchPath_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matchPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uri_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(matchPath_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, matchPath_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uri_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(matchPath_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, matchPath_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof PacketOuterClass.Packet.Args)) {
          return super.equals(obj);
        }
        PacketOuterClass.Packet.Args other = (PacketOuterClass.Packet.Args) obj;

        if (!getPath()
            .equals(other.getPath())) return false;
        if (!getUri()
            .equals(other.getUri())) return false;
        if (!getMatchPath()
            .equals(other.getMatchPath())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
        hash = (37 * hash) + URI_FIELD_NUMBER;
        hash = (53 * hash) + getUri().hashCode();
        hash = (37 * hash) + MATCH_PATH_FIELD_NUMBER;
        hash = (53 * hash) + getMatchPath().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static PacketOuterClass.Packet.Args parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PacketOuterClass.Packet.Args parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PacketOuterClass.Packet.Args parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PacketOuterClass.Packet.Args parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PacketOuterClass.Packet.Args parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PacketOuterClass.Packet.Args parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PacketOuterClass.Packet.Args parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PacketOuterClass.Packet.Args parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static PacketOuterClass.Packet.Args parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static PacketOuterClass.Packet.Args parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static PacketOuterClass.Packet.Args parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PacketOuterClass.Packet.Args parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(PacketOuterClass.Packet.Args prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code KasperCommons.Authenticator.Packet.Args}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:KasperCommons.Authenticator.Packet.Args)
          PacketOuterClass.Packet.ArgsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_Args_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_Args_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PacketOuterClass.Packet.Args.class, PacketOuterClass.Packet.Args.Builder.class);
        }

        // Construct using PacketOuterClass.Packet.Args.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          path_ = "";
          uri_ = "";
          matchPath_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_Args_descriptor;
        }

        @java.lang.Override
        public PacketOuterClass.Packet.Args getDefaultInstanceForType() {
          return PacketOuterClass.Packet.Args.getDefaultInstance();
        }

        @java.lang.Override
        public PacketOuterClass.Packet.Args build() {
          PacketOuterClass.Packet.Args result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public PacketOuterClass.Packet.Args buildPartial() {
          PacketOuterClass.Packet.Args result = new PacketOuterClass.Packet.Args(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(PacketOuterClass.Packet.Args result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.path_ = path_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.uri_ = uri_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.matchPath_ = matchPath_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PacketOuterClass.Packet.Args) {
            return mergeFrom((PacketOuterClass.Packet.Args)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PacketOuterClass.Packet.Args other) {
          if (other == PacketOuterClass.Packet.Args.getDefaultInstance()) return this;
          if (!other.getPath().isEmpty()) {
            path_ = other.path_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.getUri().isEmpty()) {
            uri_ = other.uri_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (!other.getMatchPath().isEmpty()) {
            matchPath_ = other.matchPath_;
            bitField0_ |= 0x00000004;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  path_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  uri_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  matchPath_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object path_ = "";
        /**
         * <code>string path = 1;</code>
         * @return The path.
         */
        public java.lang.String getPath() {
          java.lang.Object ref = path_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            path_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string path = 1;</code>
         * @return The bytes for path.
         */
        public com.google.protobuf.ByteString
            getPathBytes() {
          java.lang.Object ref = path_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            path_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string path = 1;</code>
         * @param value The path to set.
         * @return This builder for chaining.
         */
        public Builder setPath(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          path_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string path = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearPath() {
          path_ = getDefaultInstance().getPath();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string path = 1;</code>
         * @param value The bytes for path to set.
         * @return This builder for chaining.
         */
        public Builder setPathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          path_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private java.lang.Object uri_ = "";
        /**
         * <code>string uri = 2;</code>
         * @return The uri.
         */
        public java.lang.String getUri() {
          java.lang.Object ref = uri_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uri_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string uri = 2;</code>
         * @return The bytes for uri.
         */
        public com.google.protobuf.ByteString
            getUriBytes() {
          java.lang.Object ref = uri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string uri = 2;</code>
         * @param value The uri to set.
         * @return This builder for chaining.
         */
        public Builder setUri(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          uri_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string uri = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearUri() {
          uri_ = getDefaultInstance().getUri();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string uri = 2;</code>
         * @param value The bytes for uri to set.
         * @return This builder for chaining.
         */
        public Builder setUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          uri_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private java.lang.Object matchPath_ = "";
        /**
         * <code>string match_path = 3;</code>
         * @return The matchPath.
         */
        public java.lang.String getMatchPath() {
          java.lang.Object ref = matchPath_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            matchPath_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string match_path = 3;</code>
         * @return The bytes for matchPath.
         */
        public com.google.protobuf.ByteString
            getMatchPathBytes() {
          java.lang.Object ref = matchPath_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            matchPath_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string match_path = 3;</code>
         * @param value The matchPath to set.
         * @return This builder for chaining.
         */
        public Builder setMatchPath(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          matchPath_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>string match_path = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearMatchPath() {
          matchPath_ = getDefaultInstance().getMatchPath();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>string match_path = 3;</code>
         * @param value The bytes for matchPath to set.
         * @return This builder for chaining.
         */
        public Builder setMatchPathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          matchPath_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:KasperCommons.Authenticator.Packet.Args)
      }

      // @@protoc_insertion_point(class_scope:KasperCommons.Authenticator.Packet.Args)
      private static final PacketOuterClass.Packet.Args DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PacketOuterClass.Packet.Args();
      }

      public static PacketOuterClass.Packet.Args getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Args>
          PARSER = new com.google.protobuf.AbstractParser<Args>() {
        @java.lang.Override
        public Args parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Args> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Args> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public PacketOuterClass.Packet.Args getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface ExceptionDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:KasperCommons.Authenticator.Packet.ExceptionData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 exception_type = 1;</code>
       * @return The exceptionType.
       */
      int getExceptionType();

      /**
       * <code>string exception_message = 2;</code>
       * @return The exceptionMessage.
       */
      java.lang.String getExceptionMessage();
      /**
       * <code>string exception_message = 2;</code>
       * @return The bytes for exceptionMessage.
       */
      com.google.protobuf.ByteString
          getExceptionMessageBytes();
    }
    /**
     * Protobuf type {@code KasperCommons.Authenticator.Packet.ExceptionData}
     */
    public static final class ExceptionData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:KasperCommons.Authenticator.Packet.ExceptionData)
        ExceptionDataOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ExceptionData.newBuilder() to construct.
      private ExceptionData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ExceptionData() {
        exceptionMessage_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ExceptionData();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_ExceptionData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_ExceptionData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PacketOuterClass.Packet.ExceptionData.class, PacketOuterClass.Packet.ExceptionData.Builder.class);
      }

      public static final int EXCEPTION_TYPE_FIELD_NUMBER = 1;
      private int exceptionType_ = 0;
      /**
       * <code>int32 exception_type = 1;</code>
       * @return The exceptionType.
       */
      @java.lang.Override
      public int getExceptionType() {
        return exceptionType_;
      }

      public static final int EXCEPTION_MESSAGE_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object exceptionMessage_ = "";
      /**
       * <code>string exception_message = 2;</code>
       * @return The exceptionMessage.
       */
      @java.lang.Override
      public java.lang.String getExceptionMessage() {
        java.lang.Object ref = exceptionMessage_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exceptionMessage_ = s;
          return s;
        }
      }
      /**
       * <code>string exception_message = 2;</code>
       * @return The bytes for exceptionMessage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getExceptionMessageBytes() {
        java.lang.Object ref = exceptionMessage_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exceptionMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (exceptionType_ != 0) {
          output.writeInt32(1, exceptionType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exceptionMessage_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, exceptionMessage_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (exceptionType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, exceptionType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exceptionMessage_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, exceptionMessage_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof PacketOuterClass.Packet.ExceptionData)) {
          return super.equals(obj);
        }
        PacketOuterClass.Packet.ExceptionData other = (PacketOuterClass.Packet.ExceptionData) obj;

        if (getExceptionType()
            != other.getExceptionType()) return false;
        if (!getExceptionMessage()
            .equals(other.getExceptionMessage())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + EXCEPTION_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getExceptionType();
        hash = (37 * hash) + EXCEPTION_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getExceptionMessage().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static PacketOuterClass.Packet.ExceptionData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static PacketOuterClass.Packet.ExceptionData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PacketOuterClass.Packet.ExceptionData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(PacketOuterClass.Packet.ExceptionData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code KasperCommons.Authenticator.Packet.ExceptionData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:KasperCommons.Authenticator.Packet.ExceptionData)
          PacketOuterClass.Packet.ExceptionDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_ExceptionData_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_ExceptionData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PacketOuterClass.Packet.ExceptionData.class, PacketOuterClass.Packet.ExceptionData.Builder.class);
        }

        // Construct using PacketOuterClass.Packet.ExceptionData.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          exceptionType_ = 0;
          exceptionMessage_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_ExceptionData_descriptor;
        }

        @java.lang.Override
        public PacketOuterClass.Packet.ExceptionData getDefaultInstanceForType() {
          return PacketOuterClass.Packet.ExceptionData.getDefaultInstance();
        }

        @java.lang.Override
        public PacketOuterClass.Packet.ExceptionData build() {
          PacketOuterClass.Packet.ExceptionData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public PacketOuterClass.Packet.ExceptionData buildPartial() {
          PacketOuterClass.Packet.ExceptionData result = new PacketOuterClass.Packet.ExceptionData(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(PacketOuterClass.Packet.ExceptionData result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.exceptionType_ = exceptionType_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.exceptionMessage_ = exceptionMessage_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PacketOuterClass.Packet.ExceptionData) {
            return mergeFrom((PacketOuterClass.Packet.ExceptionData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PacketOuterClass.Packet.ExceptionData other) {
          if (other == PacketOuterClass.Packet.ExceptionData.getDefaultInstance()) return this;
          if (other.getExceptionType() != 0) {
            setExceptionType(other.getExceptionType());
          }
          if (!other.getExceptionMessage().isEmpty()) {
            exceptionMessage_ = other.exceptionMessage_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  exceptionType_ = input.readInt32();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 18: {
                  exceptionMessage_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int exceptionType_ ;
        /**
         * <code>int32 exception_type = 1;</code>
         * @return The exceptionType.
         */
        @java.lang.Override
        public int getExceptionType() {
          return exceptionType_;
        }
        /**
         * <code>int32 exception_type = 1;</code>
         * @param value The exceptionType to set.
         * @return This builder for chaining.
         */
        public Builder setExceptionType(int value) {

          exceptionType_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>int32 exception_type = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearExceptionType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          exceptionType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object exceptionMessage_ = "";
        /**
         * <code>string exception_message = 2;</code>
         * @return The exceptionMessage.
         */
        public java.lang.String getExceptionMessage() {
          java.lang.Object ref = exceptionMessage_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            exceptionMessage_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string exception_message = 2;</code>
         * @return The bytes for exceptionMessage.
         */
        public com.google.protobuf.ByteString
            getExceptionMessageBytes() {
          java.lang.Object ref = exceptionMessage_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            exceptionMessage_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string exception_message = 2;</code>
         * @param value The exceptionMessage to set.
         * @return This builder for chaining.
         */
        public Builder setExceptionMessage(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          exceptionMessage_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string exception_message = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearExceptionMessage() {
          exceptionMessage_ = getDefaultInstance().getExceptionMessage();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string exception_message = 2;</code>
         * @param value The bytes for exceptionMessage to set.
         * @return This builder for chaining.
         */
        public Builder setExceptionMessageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          exceptionMessage_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:KasperCommons.Authenticator.Packet.ExceptionData)
      }

      // @@protoc_insertion_point(class_scope:KasperCommons.Authenticator.Packet.ExceptionData)
      private static final PacketOuterClass.Packet.ExceptionData DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PacketOuterClass.Packet.ExceptionData();
      }

      public static PacketOuterClass.Packet.ExceptionData getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ExceptionData>
          PARSER = new com.google.protobuf.AbstractParser<ExceptionData>() {
        @java.lang.Override
        public ExceptionData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<ExceptionData> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ExceptionData> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public PacketOuterClass.Packet.ExceptionData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private int header_ = 0;
    /**
     * <code>int32 header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public int getHeader() {
      return header_;
    }

    public static final int ARGS_FIELD_NUMBER = 2;
    private static final class ArgsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_ArgsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> args_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetArgs() {
      if (args_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ArgsDefaultEntryHolder.defaultEntry);
      }
      return args_;
    }
    public int getArgsCount() {
      return internalGetArgs().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    @java.lang.Override
    public boolean containsArgs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetArgs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getArgsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getArgs() {
      return getArgsMap();
    }
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getArgsMap() {
      return internalGetArgs().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getArgsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetArgs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; args = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getArgsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetArgs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int DATA_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object data_ = "";
    /**
     * <code>string data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 3;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCEPTION_FIELD_NUMBER = 4;
    private int exception_ = 0;
    /**
     * <code>int32 exception = 4;</code>
     * @return The exception.
     */
    @java.lang.Override
    public int getException() {
      return exception_;
    }

    public static final int EXCEPTION_MESSAGE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object exceptionMessage_ = "";
    /**
     * <code>string exception_message = 5;</code>
     * @return The exceptionMessage.
     */
    @java.lang.Override
    public java.lang.String getExceptionMessage() {
      java.lang.Object ref = exceptionMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exceptionMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string exception_message = 5;</code>
     * @return The bytes for exceptionMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExceptionMessageBytes() {
      java.lang.Object ref = exceptionMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exceptionMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != 0) {
        output.writeInt32(1, header_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetArgs(),
          ArgsDefaultEntryHolder.defaultEntry,
          2);
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
      }
      if (exception_ != 0) {
        output.writeInt32(4, exception_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exceptionMessage_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, exceptionMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, header_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetArgs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        args__ = ArgsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, args__);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
      }
      if (exception_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, exception_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exceptionMessage_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, exceptionMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PacketOuterClass.Packet)) {
        return super.equals(obj);
      }
      PacketOuterClass.Packet other = (PacketOuterClass.Packet) obj;

      if (getHeader()
          != other.getHeader()) return false;
      if (!internalGetArgs().equals(
          other.internalGetArgs())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getException()
          != other.getException()) return false;
      if (!getExceptionMessage()
          .equals(other.getExceptionMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader();
      if (!internalGetArgs().getMap().isEmpty()) {
        hash = (37 * hash) + ARGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetArgs().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
      hash = (53 * hash) + getException();
      hash = (37 * hash) + EXCEPTION_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getExceptionMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PacketOuterClass.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PacketOuterClass.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PacketOuterClass.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PacketOuterClass.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PacketOuterClass.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PacketOuterClass.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PacketOuterClass.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PacketOuterClass.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PacketOuterClass.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PacketOuterClass.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PacketOuterClass.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PacketOuterClass.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PacketOuterClass.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KasperCommons.Authenticator.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KasperCommons.Authenticator.Packet)
        PacketOuterClass.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetArgs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableArgs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PacketOuterClass.Packet.class, PacketOuterClass.Packet.Builder.class);
      }

      // Construct using PacketOuterClass.Packet.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = 0;
        internalGetMutableArgs().clear();
        data_ = "";
        exception_ = 0;
        exceptionMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PacketOuterClass.internal_static_KasperCommons_Authenticator_Packet_descriptor;
      }

      @java.lang.Override
      public PacketOuterClass.Packet getDefaultInstanceForType() {
        return PacketOuterClass.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public PacketOuterClass.Packet build() {
        PacketOuterClass.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PacketOuterClass.Packet buildPartial() {
        PacketOuterClass.Packet result = new PacketOuterClass.Packet(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PacketOuterClass.Packet result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = header_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.args_ = internalGetArgs();
          result.args_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.exception_ = exception_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.exceptionMessage_ = exceptionMessage_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PacketOuterClass.Packet) {
          return mergeFrom((PacketOuterClass.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PacketOuterClass.Packet other) {
        if (other == PacketOuterClass.Packet.getDefaultInstance()) return this;
        if (other.getHeader() != 0) {
          setHeader(other.getHeader());
        }
        internalGetMutableArgs().mergeFrom(
            other.internalGetArgs());
        bitField0_ |= 0x00000002;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getException() != 0) {
          setException(other.getException());
        }
        if (!other.getExceptionMessage().isEmpty()) {
          exceptionMessage_ = other.exceptionMessage_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                header_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                args__ = input.readMessage(
                    ArgsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableArgs().getMutableMap().put(
                    args__.getKey(), args__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                data_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                exception_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                exceptionMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int header_ ;
      /**
       * <code>int32 header = 1;</code>
       * @return The header.
       */
      @java.lang.Override
      public int getHeader() {
        return header_;
      }
      /**
       * <code>int32 header = 1;</code>
       * @param value The header to set.
       * @return This builder for chaining.
       */
      public Builder setHeader(int value) {

        header_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 header = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> args_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetArgs() {
        if (args_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ArgsDefaultEntryHolder.defaultEntry);
        }
        return args_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableArgs() {
        if (args_ == null) {
          args_ = com.google.protobuf.MapField.newMapField(
              ArgsDefaultEntryHolder.defaultEntry);
        }
        if (!args_.isMutable()) {
          args_ = args_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return args_;
      }
      public int getArgsCount() {
        return internalGetArgs().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; args = 2;</code>
       */
      @java.lang.Override
      public boolean containsArgs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetArgs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getArgsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getArgs() {
        return getArgsMap();
      }
      /**
       * <code>map&lt;string, string&gt; args = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getArgsMap() {
        return internalGetArgs().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; args = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getArgsOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetArgs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; args = 2;</code>
       */
      @java.lang.Override
      public java.lang.String getArgsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetArgs().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearArgs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableArgs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; args = 2;</code>
       */
      public Builder removeArgs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableArgs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableArgs() {
        bitField0_ |= 0x00000002;
        return internalGetMutableArgs().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; args = 2;</code>
       */
      public Builder putArgs(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableArgs().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; args = 2;</code>
       */
      public Builder putAllArgs(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableArgs().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 3;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = getDefaultInstance().getData();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int exception_ ;
      /**
       * <code>int32 exception = 4;</code>
       * @return The exception.
       */
      @java.lang.Override
      public int getException() {
        return exception_;
      }
      /**
       * <code>int32 exception = 4;</code>
       * @param value The exception to set.
       * @return This builder for chaining.
       */
      public Builder setException(int value) {

        exception_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 exception = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000008);
        exception_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object exceptionMessage_ = "";
      /**
       * <code>string exception_message = 5;</code>
       * @return The exceptionMessage.
       */
      public java.lang.String getExceptionMessage() {
        java.lang.Object ref = exceptionMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exceptionMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exception_message = 5;</code>
       * @return The bytes for exceptionMessage.
       */
      public com.google.protobuf.ByteString
          getExceptionMessageBytes() {
        java.lang.Object ref = exceptionMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exceptionMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exception_message = 5;</code>
       * @param value The exceptionMessage to set.
       * @return This builder for chaining.
       */
      public Builder setExceptionMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        exceptionMessage_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string exception_message = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExceptionMessage() {
        exceptionMessage_ = getDefaultInstance().getExceptionMessage();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string exception_message = 5;</code>
       * @param value The bytes for exceptionMessage to set.
       * @return This builder for chaining.
       */
      public Builder setExceptionMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        exceptionMessage_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KasperCommons.Authenticator.Packet)
    }

    // @@protoc_insertion_point(class_scope:KasperCommons.Authenticator.Packet)
    private static final PacketOuterClass.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PacketOuterClass.Packet();
    }

    public static PacketOuterClass.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PacketOuterClass.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KasperCommons_Authenticator_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KasperCommons_Authenticator_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KasperCommons_Authenticator_Packet_Args_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KasperCommons_Authenticator_Packet_Args_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KasperCommons_Authenticator_Packet_ExceptionData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KasperCommons_Authenticator_Packet_ExceptionData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KasperCommons_Authenticator_Packet_ArgsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KasperCommons_Authenticator_Packet_ArgsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Packet.proto\022\033KasperCommons.Authentica" +
      "tor\"\271\002\n\006Packet\022\016\n\006header\030\001 \001(\005\022;\n\004args\030\002" +
      " \003(\0132-.KasperCommons.Authenticator.Packe" +
      "t.ArgsEntry\022\014\n\004data\030\003 \001(\t\022\021\n\texception\030\004" +
      " \001(\005\022\031\n\021exception_message\030\005 \001(\t\0325\n\004Args\022" +
      "\014\n\004path\030\001 \001(\t\022\013\n\003uri\030\002 \001(\t\022\022\n\nmatch_path" +
      "\030\003 \001(\t\032B\n\rExceptionData\022\026\n\016exception_typ" +
      "e\030\001 \001(\005\022\031\n\021exception_message\030\002 \001(\t\032+\n\tAr" +
      "gsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_KasperCommons_Authenticator_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KasperCommons_Authenticator_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KasperCommons_Authenticator_Packet_descriptor,
        new java.lang.String[] { "Header", "Args", "Data", "Exception", "ExceptionMessage", });
    internal_static_KasperCommons_Authenticator_Packet_Args_descriptor =
      internal_static_KasperCommons_Authenticator_Packet_descriptor.getNestedTypes().get(0);
    internal_static_KasperCommons_Authenticator_Packet_Args_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KasperCommons_Authenticator_Packet_Args_descriptor,
        new java.lang.String[] { "Path", "Uri", "MatchPath", });
    internal_static_KasperCommons_Authenticator_Packet_ExceptionData_descriptor =
      internal_static_KasperCommons_Authenticator_Packet_descriptor.getNestedTypes().get(1);
    internal_static_KasperCommons_Authenticator_Packet_ExceptionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KasperCommons_Authenticator_Packet_ExceptionData_descriptor,
        new java.lang.String[] { "ExceptionType", "ExceptionMessage", });
    internal_static_KasperCommons_Authenticator_Packet_ArgsEntry_descriptor =
      internal_static_KasperCommons_Authenticator_Packet_descriptor.getNestedTypes().get(2);
    internal_static_KasperCommons_Authenticator_Packet_ArgsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KasperCommons_Authenticator_Packet_ArgsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
